@startuml
start

if (自主下单) then (yes)
  :place order;
  :pay & approval & authorize;
  :handle ticketApplyConfirm task;
   
  if (出票申请任务执行成功) then (yes)
  else (no) 
    :handle cancelOrder task;
    :cancel pnr (auto or handle task);
    stop
  endif

else (no)
  :build order;
  :pay;

endif

:handle ticketConfirm task;
  
if (出票任务执行成功) then (yes)
else (no) 
  :cancel order; 
endif

stop
@enduml
